### ISSUE TITLE
the rename button does not work

### ISSUE THREAD

**Issue by mishatsht** [JusticeRage/Gepetto#14] opened 2023-02-12 06:45 UTC

**Comment by JusticeRage** [comment] 2023-02-12 13:04
Please provide details for this bug. The rename button seems to be working for everyone else. Share any log message appearing in IDA's output window, or maybe the IDB in which the problem appears. Without any information, I will be unable to reproduce the bug and have no option but to close this issue.

**Comment by JusticeRage** [comment] 2023-02-25 13:04
Closing due to lack of information.

**Comment by JusticeRage** [comment] 2023-04-26 20:52
I appreciate the fix, but I still don't understand what the problem is... Could anyone clarify what the bug is and how to trigger it?

**Comment by FBLeee** [comment] 2023-04-27 01:05
> I appreciate the fix, but I still don't understand what the problem is... Could anyone clarify what the bug is and how to trigger it?
There is a problem with this code（line 200）. The rename_lvar of ida_hexrays does not work. Is it caused by different IDA versions?
```
  for n in names:
         if ida_hexrays.rename_lvar(function_addr, n, names[n]):
             replaced.append(n)
```

**Closed** 2023-05-31 15:19 UTC
Labels: invalid
